from __future__ import annotations

from typing import Any

AXIS_PRESENTATION_SCHEMA_VERSION = "axis_presentation_v1"

# User-facing labels live here. Registry IDs remain the canonical API/YAML
# values; labels are the docs/Navigator surface shown to researchers.
AXIS_PRESENTATION_MAP: dict[str, dict[str, Any]] = {
    "study_scope": {
        "order": 1,
        "label": "Study Scope",
        "short_label": "Scope",
        "question": "How many targets and methods should this study compare?",
        "summary": "Sets target cardinality and whether the method path is fixed or compared across alternatives.",
        "docs_url": "../detail/layer0/study_scope.html",
        "contract": "Primary Layer 0 study-shape contract. It derives the Layer 1 target_structure and determines whether downstream method axes are fixed or sweep-aware.",
        "selection_kind": "user_choice",
        "values": {
            "one_target_one_method": {
                "label": "One Target, One Method",
                "short_label": "1 Target / 1 Method",
                "summary": "Use one target and one fixed forecasting method path.",
            },
            "one_target_compare_methods": {
                "label": "One Target, Compare Methods",
                "short_label": "1 Target / Compare",
                "summary": "Use one target and compare multiple model, representation, preprocessing, horizon, or tuning choices.",
            },
            "multiple_targets_one_method": {
                "label": "Multiple Targets, One Method",
                "short_label": "Multi Target / 1 Method",
                "summary": "Use multiple targets and one fixed forecasting method path shared across targets.",
            },
            "multiple_targets_compare_methods": {
                "label": "Multiple Targets, Compare Methods",
                "short_label": "Multi Target / Compare",
                "summary": "Use multiple targets and compare one or more downstream method axes across the same study.",
            },
        },
    },
    "failure_policy": {
        "order": 2,
        "label": "Failure Handling",
        "short_label": "Failures",
        "question": "What should happen when a run, variant, or cell fails?",
        "summary": "Controls whether the run stops, skips failed units, warns, or preserves partial results.",
        "docs_url": "../detail/layer0/failure_policy.html",
        "contract": "Runtime failure contract. Sweep-compatible modes decide whether invalid variants stop or are skipped.",
        "selection_kind": "defaulted_choice",
        "default_value": "fail_fast",
        "values": {
            "fail_fast": {
                "label": "Stop on First Failure (Default)",
                "short_label": "Stop (Default)",
                "summary": "Default. Abort immediately so the first error can be investigated.",
            },
            "skip_failed_cell": {
                "label": "Skip Failed Sweep Cells",
                "short_label": "Skip Cells",
                "summary": "Continue a sweep while recording failed variant status.",
            },
            "skip_failed_model": {
                "label": "Skip Failed Model Branches",
                "short_label": "Skip Models",
                "summary": "Continue after failures scoped to one model branch.",
            },
            "save_partial_results": {
                "label": "Save Partial Results",
                "short_label": "Save Partial",
                "summary": "Persist completed artifacts before aborting or reporting failure.",
            },
            "warn_only": {
                "label": "Warn Only",
                "short_label": "Warn",
                "summary": "Emit warnings and continue when failures are recoverable.",
            },
        },
    },
    "reproducibility_mode": {
        "order": 3,
        "label": "Reproducibility",
        "short_label": "Reproducibility",
        "question": "How strictly should stochastic components be pinned?",
        "summary": "Controls seeds and deterministic-library settings before model execution.",
        "docs_url": "../detail/layer0/reproducibility_mode.html",
        "contract": "Seed and determinism contract applied before stochastic model code runs.",
        "selection_kind": "defaulted_choice",
        "default_value": "seeded_reproducible",
        "values": {
            "strict_reproducible": {
                "label": "Strict Reproducible Run",
                "short_label": "Strict",
                "summary": "Use deterministic-library settings for replication-grade reruns.",
            },
            "seeded_reproducible": {
                "label": "Seeded Run (Default)",
                "short_label": "Seeded (Default)",
                "summary": "Default. Seed Python, NumPy, and optional torch without strict backend flags.",
            },
            "best_effort": {
                "label": "Best-Effort Seeded Run",
                "short_label": "Best Effort",
                "summary": "Apply available seeds and mark the run as non-strict.",
            },
            "exploratory": {
                "label": "Exploratory Run",
                "short_label": "Exploratory",
                "summary": "Do not force deterministic behavior.",
            },
        },
    },
    "compute_mode": {
        "order": 4,
        "label": "Compute Layout",
        "short_label": "Compute",
        "question": "How should execution work be laid out?",
        "summary": "Default to serial execution, or request local parallelism over models, horizons, targets, or OOS dates.",
        "docs_url": "../detail/layer0/compute_mode.html",
        "contract": "Execution layout contract. Singleton work units degrade to serial/no-op behavior.",
        "selection_kind": "defaulted_choice",
        "default_value": "serial",
        "values": {
            "serial": {
                "label": "Serial (Default)",
                "short_label": "Serial (Default)",
                "summary": "Default. Run one unit of work at a time.",
            },
            "parallel_by_model": {
                "label": "Parallelize Model Variants",
                "short_label": "By Model",
                "summary": "Parallelize across model-family variants when a model sweep exists.",
            },
            "parallel_by_horizon": {
                "label": "Parallelize Forecast Horizons",
                "short_label": "By Horizon",
                "summary": "Parallelize across forecast horizons when multiple horizons exist.",
            },
            "parallel_by_target": {
                "label": "Parallelize Targets",
                "short_label": "By Target",
                "summary": "Parallelize across targets in a multi-target run.",
            },
            "parallel_by_oos_date": {
                "label": "Parallelize OOS Dates",
                "short_label": "By OOS Date",
                "summary": "Parallelize across origin dates in a long pseudo-OOS window.",
            },
        },
    },
    "dataset": {
        "order": 5,
        "label": "Source Panel",
        "short_label": "Source",
        "question": "Which official source panel starts the study?",
        "summary": "Selects the official FRED-family panel before optional custom-file use, target, timing, or representation decisions.",
        "docs_url": "../detail/layer1/source_frame.html",
        "contract": "Layer 1 source contract. FRED-MD implies monthly data, FRED-QD implies quarterly data, and standalone FRED-SD requires an explicit frequency. User-supplied files are configured by the custom source axes, not by this source-panel axis.",
        "selection_kind": "user_choice",
        "values": {
            "fred_md": {
                "label": "FRED-MD",
                "short_label": "FRED-MD",
                "summary": "Monthly national macro panel with official transform codes.",
            },
            "fred_qd": {
                "label": "FRED-QD",
                "short_label": "FRED-QD",
                "summary": "Quarterly national macro panel with official transform codes.",
            },
            "fred_sd": {
                "label": "FRED-SD",
                "short_label": "FRED-SD",
                "summary": "State-level panel; choose monthly or quarterly frequency explicitly.",
            },
            "fred_md+fred_sd": {
                "label": "FRED-MD + FRED-SD",
                "short_label": "MD + SD",
                "summary": "Monthly national panel plus state-level source columns.",
            },
            "fred_qd+fred_sd": {
                "label": "FRED-QD + FRED-SD",
                "short_label": "QD + SD",
                "summary": "Quarterly national panel plus state-level source columns.",
            },
        },
    },
    "custom_source_policy": {
        "order": 6,
        "label": "Custom Data Use",
        "short_label": "Custom Data",
        "question": "Do you want official data, your own data, or official data plus your own data?",
        "summary": "Choose official data only, custom panel only, or official data plus custom columns.",
        "docs_url": "../detail/layer1/source_frame.html",
        "contract": "When a custom source is selected, choose custom_source_format and custom_source_schema, then provide leaf_config.custom_source_path. custom_panel_only supports one official source panel; official_plus_custom supports single or composite official panels.",
        "warning": "Custom files must follow the frequency and schema contract in the docs before the run is reproducible.",
        "selection_kind": "defaulted_choice",
        "default_value": "official_only",
        "values": {
            "official_only": {
                "label": "Use Official Data Only (Default)",
                "short_label": "Official Only",
                "summary": "Use only the selected official FRED source panel.",
            },
            "custom_panel_only": {
                "label": "Use My Data Only",
                "short_label": "My Data Only",
                "summary": "Use a custom file instead of the selected single official source panel. The custom schema must match the selected source panel.",
            },
            "official_plus_custom": {
                "label": "Add My Data To Official Data",
                "short_label": "Official + Mine",
                "summary": "Load the selected official source panel and append custom columns after frequency alignment.",
            },
        },
    },
    "custom_source_format": {
        "order": 6.2,
        "label": "Custom File Format",
        "short_label": "Custom Format",
        "question": "What file format does the custom source use?",
        "summary": "Active only when Custom Data Use is My Data Only or Official + Mine.",
        "docs_url": "../detail/layer1/source_frame.html",
        "contract": "Use csv for a date-indexed CSV panel and parquet for a Parquet panel. Use none when no custom source is selected.",
        "warning": "Check the detailed docs for required date index and numeric-column shape.",
        "selection_kind": "conditional_choice",
        "default_value": "none",
        "values": {
            "none": {
                "label": "No Custom File (Default)",
                "short_label": "None",
                "summary": "No custom source file is used.",
            },
            "csv": {
                "label": "CSV",
                "short_label": "CSV",
                "summary": "A date-indexed CSV file with numeric series columns.",
            },
            "parquet": {
                "label": "Parquet",
                "short_label": "Parquet",
                "summary": "A Parquet file with a DatetimeIndex or parseable date first column.",
            },
        },
    },
    "custom_source_schema": {
        "order": 6.4,
        "label": "Custom File Schema",
        "short_label": "Custom Schema",
        "question": "Which official panel schema does the custom file follow?",
        "summary": "Active only when a custom file is selected. My Data Only must match the selected Source Panel; Official + Mine may use MD, QD, or SD-like columns.",
        "docs_url": "../detail/layer1/source_frame.html",
        "contract": "Use none with official_only. Use fred_md for monthly national macro panels, fred_qd for quarterly national macro panels, and fred_sd for state-level panels that will be aligned to the selected Layer 1 frequency.",
        "warning": "This is a schema contract, not a loader choice. The file path still lives in leaf_config.custom_source_path.",
        "selection_kind": "conditional_choice",
        "default_value": "none",
        "values": {
            "none": {
                "label": "No Custom Schema (Default)",
                "short_label": "None",
                "summary": "No custom file is used.",
            },
            "fred_md": {
                "label": "FRED-MD-Like Monthly Panel",
                "short_label": "MD-like",
                "summary": "Date-indexed monthly national macro columns named like series IDs.",
            },
            "fred_qd": {
                "label": "FRED-QD-Like Quarterly Panel",
                "short_label": "QD-like",
                "summary": "Date-indexed quarterly national macro columns named like series IDs.",
            },
            "fred_sd": {
                "label": "FRED-SD-Like State Panel",
                "short_label": "SD-like",
                "summary": "Date-indexed state-level columns, normally monthly before Layer 1 alignment.",
            },
        },
    },
    "frequency": {
        "order": 7,
        "label": "Frequency",
        "short_label": "Frequency",
        "question": "What calendar frequency should the official frame use?",
        "summary": "Derived for FRED-MD/QD/composites and required for standalone FRED-SD.",
        "docs_url": "../detail/layer1/source_frame.html",
        "contract": "Frequency contract. FRED-MD routes are monthly, FRED-QD routes are quarterly, and FRED-SD-only routes choose one explicitly.",
        "selection_kind": "derived_or_required_choice",
        "values": {
            "monthly": {
                "label": "Monthly",
                "short_label": "Monthly",
                "summary": "Monthly official frame.",
            },
            "quarterly": {
                "label": "Quarterly",
                "short_label": "Quarterly",
                "summary": "Quarterly official frame.",
            },
        },
    },
    "information_set_type": {
        "order": 8,
        "label": "Information Set",
        "short_label": "Info Set",
        "question": "Which data-availability regime defines the source frame?",
        "summary": "Simple runs use final revised data; pseudo-OOS revised data applies forecasting-time availability discipline on revised data.",
        "docs_url": "../detail/layer1/source_frame.html",
        "contract": "Information-set contract consumed before representation construction.",
        "selection_kind": "defaulted_choice",
        "default_value": "final_revised_data",
        "values": {
            "final_revised_data": {
                "label": "Final Revised Data (Default)",
                "short_label": "Final Revised",
                "summary": "Default. Use the final revised panel.",
            },
            "pseudo_oos_on_revised_data": {
                "label": "Pseudo-OOS on Revised Data",
                "short_label": "Pseudo-OOS Revised",
                "summary": "Use revised data while applying pseudo-out-of-sample availability discipline.",
            },
        },
    },
    "fred_sd_frequency_policy": {
        "order": 9,
        "label": "FRED-SD Frequency Gate",
        "short_label": "SD Frequency",
        "question": "How strictly should FRED-SD native-frequency evidence be enforced?",
        "summary": "No-op unless the dataset includes FRED-SD; non-default values gate mixed native frequencies.",
        "docs_url": "../detail/layer1/fred_sd_source_selection.html",
        "contract": "FRED-SD source-evidence contract. Layer 2 consumes the resulting native-frequency report for representation choices.",
        "selection_kind": "defaulted_choice",
        "default_value": "report_only",
        "values": {
            "report_only": {
                "label": "Report Only (Default)",
                "short_label": "Report Only",
                "summary": "Default. Record native-frequency evidence without rejecting series.",
            },
            "allow_mixed_frequency": {
                "label": "Allow Mixed Frequencies",
                "short_label": "Allow Mixed",
                "summary": "Accept mixed known native frequencies after reporting them.",
            },
            "reject_mixed_known_frequency": {
                "label": "Reject Mixed Known Frequencies",
                "short_label": "Reject Mixed",
                "summary": "Fail if selected FRED-SD series contain multiple known native frequencies.",
            },
            "require_single_known_frequency": {
                "label": "Require Single Known Frequency",
                "short_label": "Require Single",
                "summary": "Require all selected FRED-SD series to share one known native frequency.",
            },
        },
    },
    "fred_sd_state_group": {
        "order": 10,
        "label": "FRED-SD State Group",
        "short_label": "SD States",
        "question": "Which state set should enter the FRED-SD source frame?",
        "summary": "No-op unless the dataset includes FRED-SD; group choices resolve to explicit state selectors.",
        "docs_url": "../detail/layer1/fred_sd_source_selection.html",
        "contract": "FRED-SD state-selection contract. Custom groups require leaf_config.sd_states.",
        "selection_kind": "defaulted_choice",
        "default_value": "all_states",
        "values": {
            "all_states": {"label": "All States (Default)", "short_label": "All States", "summary": "Use all available FRED-SD states."},
            "census_region_northeast": {"label": "Census Region: Northeast", "short_label": "Northeast", "summary": "Use Northeast region states."},
            "census_region_midwest": {"label": "Census Region: Midwest", "short_label": "Midwest", "summary": "Use Midwest region states."},
            "census_region_south": {"label": "Census Region: South", "short_label": "South", "summary": "Use South region states."},
            "census_region_west": {"label": "Census Region: West", "short_label": "West", "summary": "Use West region states."},
            "census_division_new_england": {"label": "Census Division: New England", "short_label": "New England", "summary": "Use New England division states."},
            "census_division_middle_atlantic": {"label": "Census Division: Middle Atlantic", "short_label": "Mid Atlantic", "summary": "Use Middle Atlantic division states."},
            "census_division_east_north_central": {"label": "Census Division: East North Central", "short_label": "East North Central", "summary": "Use East North Central division states."},
            "census_division_west_north_central": {"label": "Census Division: West North Central", "short_label": "West North Central", "summary": "Use West North Central division states."},
            "census_division_south_atlantic": {"label": "Census Division: South Atlantic", "short_label": "South Atlantic", "summary": "Use South Atlantic division states."},
            "census_division_east_south_central": {"label": "Census Division: East South Central", "short_label": "East South Central", "summary": "Use East South Central division states."},
            "census_division_west_south_central": {"label": "Census Division: West South Central", "short_label": "West South Central", "summary": "Use West South Central division states."},
            "census_division_mountain": {"label": "Census Division: Mountain", "short_label": "Mountain", "summary": "Use Mountain division states."},
            "census_division_pacific": {"label": "Census Division: Pacific", "short_label": "Pacific", "summary": "Use Pacific division states."},
            "contiguous_48_plus_dc": {"label": "Contiguous 48 + DC", "short_label": "48 + DC", "summary": "Use contiguous states plus District of Columbia."},
            "custom_state_group": {"label": "Custom State Group", "short_label": "Custom", "summary": "Use states supplied in leaf_config.sd_states."},
        },
    },
    "fred_sd_variable_group": {
        "order": 11,
        "label": "FRED-SD Variable Group",
        "short_label": "SD Variables",
        "question": "Which FRED-SD variable family should enter the source frame?",
        "summary": "No-op unless the dataset includes FRED-SD; group choices resolve to explicit variable selectors.",
        "docs_url": "../detail/layer1/fred_sd_source_selection.html",
        "contract": "FRED-SD variable-selection contract. Custom groups require leaf_config.sd_variables.",
        "selection_kind": "defaulted_choice",
        "default_value": "all_sd_variables",
        "values": {
            "all_sd_variables": {"label": "All FRED-SD Variables (Default)", "short_label": "All Variables", "summary": "Use all available FRED-SD variable families."},
            "labor_market_core": {"label": "Labor Market Core", "short_label": "Labor Core", "summary": "Use core labor-market variables."},
            "employment_sector": {"label": "Employment Sector", "short_label": "Employment", "summary": "Use sectoral employment variables."},
            "gsp_output": {"label": "GSP / Output", "short_label": "Output", "summary": "Use output and gross-state-product variables."},
            "housing": {"label": "Housing", "short_label": "Housing", "summary": "Use housing-market variables."},
            "trade": {"label": "Trade", "short_label": "Trade", "summary": "Use trade-related variables."},
            "income": {"label": "Income", "short_label": "Income", "summary": "Use income-related variables."},
            "direct_analog_high_confidence": {"label": "Direct Analog: High Confidence", "short_label": "High Confidence", "summary": "Use variables with strong national-panel analogs."},
            "provisional_analog_medium": {"label": "Provisional Analog: Medium", "short_label": "Medium Analog", "summary": "Use variables with provisional national-panel analogs."},
            "semantic_review_outputs": {"label": "Semantic Review Outputs", "short_label": "Semantic Review", "summary": "Use variables grouped by semantic review outputs."},
            "no_reliable_analog": {"label": "No Reliable Analog", "short_label": "No Analog", "summary": "Use variables without reliable national-panel analogs."},
            "custom_sd_variable_group": {"label": "Custom Variable Group", "short_label": "Custom", "summary": "Use variables supplied in leaf_config.sd_variables."},
        },
    },
    "target_structure": {
        "order": 12,
        "label": "Target Structure",
        "short_label": "Target",
        "question": "Is the study forecasting one target or multiple targets?",
        "summary": "Must match Layer 0 Study Scope and the target fields in leaf_config.",
        "docs_url": "../detail/layer1/target_universe.html",
        "contract": "Target cardinality contract. One-target scopes require target_structure=single_target; multiple-target scopes require target_structure=multi_target.",
        "selection_kind": "contract_choice",
        "default_value": "single_target",
        "values": {
            "single_target": {
                "label": "Single Target (Default)",
                "short_label": "Single Target",
                "summary": "Use leaf_config.target for one forecast target.",
            },
            "multi_target": {
                "label": "Multiple Targets",
                "short_label": "Multi Target",
                "summary": "Use leaf_config.targets for a target panel.",
            },
        },
    },
    "variable_universe": {
        "order": 13,
        "label": "Variable Universe",
        "short_label": "Universe",
        "question": "Which source columns are eligible before Layer 2 builds features?",
        "summary": "Filters the official source universe before representation construction.",
        "docs_url": "../detail/layer1/target_universe.html",
        "contract": "Source-column universe contract. Non-default choices require the matching leaf_config column lists or mappings.",
        "selection_kind": "defaulted_choice",
        "default_value": "all_variables",
        "values": {
            "all_variables": {"label": "All Variables (Default)", "short_label": "All", "summary": "Use the full eligible source-column universe."},
            "core_variables": {"label": "Core Variables", "short_label": "Core", "summary": "Use the package's core source-variable subset."},
            "category_variables": {"label": "Category Variables", "short_label": "Category", "summary": "Use columns mapped to a selected category."},
            "target_specific_variables": {"label": "Target-Specific Variables", "short_label": "Target-Specific", "summary": "Use per-target column mappings."},
            "explicit_variable_list": {"label": "Explicit Variable List", "short_label": "Explicit List", "summary": "Use leaf_config.variable_universe_columns."},
        },
    },
    "raw_missing_policy": {
        "order": 14,
        "label": "Raw Missing Policy",
        "short_label": "Raw Missing",
        "question": "How should missing values already present in the raw source be handled?",
        "summary": "Runs before official transforms or t-codes, so it can change transformed outputs.",
        "docs_url": "../detail/layer1/raw_source_cleaning.html",
        "contract": "Raw-source cleaning contract before official transforms. Layer 2 missing policies act later on the representation frame.",
        "selection_kind": "defaulted_choice",
        "default_value": "preserve_raw_missing",
        "values": {
            "preserve_raw_missing": {"label": "Preserve Raw Missing (Default)", "short_label": "Preserve", "summary": "Leave raw-source missing values untouched."},
            "zero_fill_leading_predictor_missing_before_tcode": {"label": "Zero-Fill Leading Predictor Gaps", "short_label": "Zero-Fill Leading", "summary": "Fill leading predictor gaps before official transforms."},
            "impute_raw_predictors": {"label": "Impute Raw Predictors", "short_label": "Impute", "summary": "Impute raw predictors using leaf_config.raw_x_imputation."},
            "drop_raw_missing_rows": {"label": "Drop Raw Missing Rows", "short_label": "Drop Rows", "summary": "Drop rows with raw-source missing values before transforms."},
        },
    },
    "raw_outlier_policy": {
        "order": 15,
        "label": "Raw Outlier Policy",
        "short_label": "Raw Outliers",
        "question": "How should outliers already present in the raw source be handled?",
        "summary": "Runs before official transforms or t-codes.",
        "docs_url": "../detail/layer1/raw_source_cleaning.html",
        "contract": "Raw-source outlier contract before official transforms. Layer 2 outlier policies act later on representation inputs.",
        "selection_kind": "defaulted_choice",
        "default_value": "preserve_raw_outliers",
        "values": {
            "preserve_raw_outliers": {"label": "Preserve Raw Outliers (Default)", "short_label": "Preserve", "summary": "Leave raw-source outliers untouched."},
            "winsorize_raw": {"label": "Winsorize Raw Values", "short_label": "Winsorize", "summary": "Winsorize raw values before transforms."},
            "iqr_clip_raw": {"label": "IQR Clip Raw Values", "short_label": "IQR Clip", "summary": "Clip raw outliers using an interquartile-range rule."},
            "mad_clip_raw": {"label": "MAD Clip Raw Values", "short_label": "MAD Clip", "summary": "Clip raw outliers using a median-absolute-deviation rule."},
            "zscore_clip_raw": {"label": "Z-Score Clip Raw Values", "short_label": "Z Clip", "summary": "Clip raw outliers using a z-score rule."},
            "set_raw_outliers_to_missing": {"label": "Set Raw Outliers to Missing", "short_label": "Set Missing", "summary": "Mark detected raw outliers as missing before later handling."},
        },
    },
    "official_transform_policy": {
        "order": 16,
        "label": "Official Transform Policy",
        "short_label": "Official T-Code",
        "question": "Should official dataset transform codes be applied?",
        "summary": "Controls official FRED-MD/QD t-code application while building the official frame.",
        "docs_url": "../detail/layer1/official_transforms.html",
        "contract": "Official-transform contract. FRED-SD inferred transforms are Layer 2 researcher-chosen transformations, not official source definitions.",
        "selection_kind": "defaulted_choice",
        "default_value": "apply_official_tcode",
        "values": {
            "apply_official_tcode": {"label": "Apply Official T-Codes (Default)", "short_label": "Apply T-Codes", "summary": "Apply official dataset transform codes."},
            "keep_official_raw_scale": {"label": "Keep Official Raw Scale", "short_label": "Keep Raw Scale", "summary": "Preserve source scale without official t-code transformation."},
        },
    },
    "official_transform_scope": {
        "order": 17,
        "label": "Official Transform Scope",
        "short_label": "T-Code Scope",
        "question": "Which columns should official transforms apply to?",
        "summary": "Chooses whether target, predictors, both, or neither receive official transforms.",
        "docs_url": "../detail/layer1/official_transforms.html",
        "contract": "Scope contract for official transform application.",
        "selection_kind": "defaulted_choice",
        "default_value": "target_and_predictors",
        "values": {
            "target_only": {"label": "Target Only", "short_label": "Target Only", "summary": "Apply official transforms only to the target."},
            "predictors_only": {"label": "Predictors Only", "short_label": "Predictors Only", "summary": "Apply official transforms only to predictors."},
            "target_and_predictors": {"label": "Target and Predictors (Default)", "short_label": "Target + X", "summary": "Default. Apply official transforms to target and predictors."},
            "none": {"label": "None", "short_label": "None", "summary": "Do not apply official transforms."},
        },
    },
    "missing_availability": {
        "order": 18,
        "label": "Availability Missing Policy",
        "short_label": "Availability",
        "question": "How should official-frame availability gaps be handled?",
        "summary": "Runs after the official frame exists and before Layer 2 representation construction.",
        "docs_url": "../detail/layer1/availability_timing.html",
        "contract": "Official-frame availability contract. This is not raw-source repair.",
        "selection_kind": "defaulted_choice",
        "default_value": "zero_fill_leading_predictor_gaps",
        "values": {
            "require_complete_rows": {"label": "Require Complete Rows", "short_label": "Complete Rows", "summary": "Keep only rows complete across the official frame."},
            "keep_available_rows": {"label": "Keep Available Rows", "short_label": "Keep Available", "summary": "Keep rows with available target/predictor information."},
            "impute_predictors_only": {"label": "Impute Predictors Only", "short_label": "Impute X", "summary": "Impute predictor gaps using leaf_config.x_imputation."},
            "zero_fill_leading_predictor_gaps": {"label": "Zero-Fill Leading Predictor Gaps (Default)", "short_label": "Zero-Fill Leading", "summary": "Default. Fill leading predictor gaps after official-frame construction."},
        },
    },
    "release_lag_rule": {
        "order": 19,
        "label": "Release Lag Rule",
        "short_label": "Release Lag",
        "question": "Should predictor release lags be simulated?",
        "summary": "Controls publication-lag discipline before Layer 2 uses the source frame.",
        "docs_url": "../detail/layer1/availability_timing.html",
        "contract": "Release-lag contract. Series-specific lag requires leaf_config.release_lag_per_series.",
        "selection_kind": "defaulted_choice",
        "default_value": "ignore_release_lag",
        "values": {
            "ignore_release_lag": {"label": "Ignore Release Lag (Default)", "short_label": "Ignore", "summary": "Default. Do not shift predictors by publication lag."},
            "fixed_lag_all_series": {"label": "Fixed Lag for All Series", "short_label": "Fixed Lag", "summary": "Apply one lag rule to all predictors."},
            "series_specific_lag": {"label": "Series-Specific Lags", "short_label": "Series-Specific", "summary": "Use per-series lags from leaf_config.release_lag_per_series."},
        },
    },
    "contemporaneous_x_rule": {
        "order": 20,
        "label": "Contemporaneous X Rule",
        "short_label": "Same-Period X",
        "question": "Can same-period predictors enter the forecast information set?",
        "summary": "Controls whether predictors observed at the target period are allowed.",
        "docs_url": "../detail/layer1/availability_timing.html",
        "contract": "Forecast information-set contract. Allowing same-period predictors is an oracle/data-leak benchmark.",
        "selection_kind": "defaulted_choice",
        "default_value": "forbid_same_period_predictors",
        "values": {
            "allow_same_period_predictors": {"label": "Allow Same-Period Predictors", "short_label": "Allow", "summary": "Oracle benchmark. Permit same-period X values."},
            "forbid_same_period_predictors": {"label": "Forbid Same-Period Predictors (Default)", "short_label": "Forbid (Default)", "summary": "Default. Use realistic forecasting information only."},
        },
    },
}


def axis_presentation_map() -> dict[str, Any]:
    return {
        axis_name: {
            **{key: value for key, value in spec.items() if key != "values"},
            "values": {value_name: dict(value_spec) for value_name, value_spec in spec.get("values", {}).items()},
        }
        for axis_name, spec in AXIS_PRESENTATION_MAP.items()
    }
