"""Pandas-first macro forecasting workflow tools."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__version__ = "0.9.5"

_LAZY_EXPORTS = {
    "DEFAULT_RANDOM_SEED": ".meta",
    "MetadataLevel": ".meta",
    "StageDefaultScope": ".meta",
    "configure": ".meta",
    "get_config": ".meta",
    "get_option": ".meta",
    "reset_config": ".meta",
    "use_config": ".meta",
    "selection_frequency_table": ".pipeline",
    "selection_history": ".pipeline",
    "axis_contribution": ".analysis",
    "DataBundle": ".data",
    "DataSpec": ".data",
    "RegimeDirection": ".data",
    "SamePeriodPolicy": ".data",
    "VintagePanelSpec": ".data",
    "VintageSource": ".data",
    "VintageUnavailableError": ".data",
    "as_panel": ".data",
    "align_frequency": ".data",
    "attach_metadata": ".data",
    "availability_lag": ".data",
    "chow_lin_disaggregate": ".data",
    "custom_vintages": ".data",
    "custom_dataset": ".data",
    "metadata": ".data",
    "panel_info": ".data",
    "set_frequencies": ".data",
    "spec": ".data",
    "validate_panel": ".data",
    "combine": ".data",
    "define_regime": ".data",
    "frequency_hardening_issues": ".data",
    "infer_frequencies": ".data",
    "list_vintages": ".data",
    "load_custom_csv": ".data",
    "load_custom_parquet": ".data",
    "load_fred_md": ".data",
    "load_fred_qd": ".data",
    "load_fred_sd": ".data",
    "load_fred_md_sd": ".data",
    "load_fred_qd_sd": ".data",
    "fred_md_vintages": ".data",
    "fred_qd_vintages": ".data",
    "same_period_predictors": ".data",
    "with_static_extras": ".data",
    "PreprocessedData": ".preprocessing",
    "FittedPreprocessor": ".preprocessing",
    "PreprocessSpec": ".preprocessing",
    "preprocess_spec": ".preprocessing",
    "custom_preprocess": ".preprocessing",
    "custom_preprocess_step": ".preprocessing",
    "reprocess": ".preprocessing",
    "standardize_panel": ".preprocessing",
    "FeatureSpec": ".feature_engineering",
    "FeatureSet": ".feature_engineering",
    "FeatureSelectionResult": ".feature_engineering",
    "FittedFeatureBuilder": ".feature_engineering",
    "adaptive_ma_rf_features": ".feature_engineering",
    "align_reference_weights": ".feature_engineering",
    "asymmetric_trim_features": ".feature_engineering",
    "average_target": ".feature_engineering",
    "boruta_selection": ".feature_engineering",
    "build_features": ".feature_engineering",
    "compose_features": ".feature_engineering",
    "correlation_selection": ".feature_engineering",
    "cumsum_features": ".feature_engineering",
    "custom_features": ".feature_engineering",
    "custom_step": ".feature_engineering",
    "dfm_features": ".feature_engineering",
    "diff_features": ".feature_engineering",
    "direct_target": ".feature_engineering",
    "feature_matrix": ".feature_engineering",
    "feature_spec": ".feature_engineering",
    "feature_selection_requires_target": ".feature_engineering",
    "fourier_features": ".feature_engineering",
    "fourier_step": ".feature_engineering",
    "forward_average_target": ".feature_engineering",
    "genetic_selection": ".feature_engineering",
    "group_pca": ".feature_engineering",
    "group_pca_step": ".feature_engineering",
    "hamilton_filter_features": ".feature_engineering",
    "hamilton_step": ".feature_engineering",
    "hp_filter_features": ".feature_engineering",
    "interaction_features": ".feature_engineering",
    "interaction_step": ".feature_engineering",
    "lag": ".feature_engineering",
    "lag_step": ".feature_engineering",
    "lags_then_pca": ".feature_engineering",
    "lasso_path_selection": ".feature_engineering",
    "lasso_selection": ".feature_engineering",
    "log_diff_features": ".feature_engineering",
    "log_features": ".feature_engineering",
    "maf_features": ".feature_engineering",
    "maf_step": ".feature_engineering",
    "marx_step": ".feature_engineering",
    "mixed_frequency_lags": ".feature_engineering",
    "moving_average_changes": ".feature_engineering",
    "moving_average_ladder": ".feature_engineering",
    "moving_average_pca_lags": ".feature_engineering",
    "moving_average_step": ".feature_engineering",
    "normalize_feature_selection_method": ".feature_engineering",
    "nystroem_features": ".feature_engineering",
    "nystroem_step": ".feature_engineering",
    "path_targets": ".feature_engineering",
    "pca_features": ".feature_engineering",
    "pca_step": ".feature_engineering",
    "pca_then_lags": ".feature_engineering",
    "partial_least_squares_features": ".feature_engineering",
    "partial_least_squares_step": ".feature_engineering",
    "predictor_screen": ".feature_engineering",
    "pct_change_features": ".feature_engineering",
    "polynomial_features": ".feature_engineering",
    "polynomial_step": ".feature_engineering",
    "random_projection_features": ".feature_engineering",
    "random_projection_step": ".feature_engineering",
    "rank_space_features": ".feature_engineering",
    "rfe_selection": ".feature_engineering",
    "rolling_mean": ".feature_engineering",
    "rolling_step": ".feature_engineering",
    "savitzky_golay_features": ".feature_engineering",
    "scale_features": ".feature_engineering",
    "scale_step": ".feature_engineering",
    "season_dummy": ".feature_engineering",
    "season_dummy_step": ".feature_engineering",
    "seasonal_lag": ".feature_engineering",
    "seasonal_lag_step": ".feature_engineering",
    "select_features": ".feature_engineering",
    "sliced_inverse_regression_features": ".feature_engineering",
    "sliced_inverse_regression_step": ".feature_engineering",
    "sparse_pca_chen_rohe_features": ".feature_engineering",
    "sparse_pca_chen_rohe_step": ".feature_engineering",
    "stability_selection": ".feature_engineering",
    "time_features": ".feature_engineering",
    "time_step": ".feature_engineering",
    "transform_step": ".feature_engineering",
    "transform_features": ".feature_engineering",
    "varimax_features": ".feature_engineering",
    "varimax_step": ".feature_engineering",
    "variance_selection": ".feature_engineering",
    "wavelet_features": ".feature_engineering",
    "weighted_aggregate": ".feature_engineering",
    "EvaluationReport": ".evaluation",
    "aggregate_scores": ".evaluation",
    "benchmark_comparison": ".evaluation",
    "error_decomposition": ".evaluation",
    "evaluate_report": ".evaluation",
    "filter_oos_period": ".evaluation",
    "regime_scores": ".evaluation",
    "ModelFit": ".models",
    "ModelParameter": ".models",
    "SavedModel": ".models",
    "LGBAPlusRegressor": ".models",
    "LGBPlusRegressor": ".models",
    "ModelSpec": ".models",
    "VolatilityFit": ".models",
    "adaptive_elastic_net": ".models",
    "adaptive_lasso": ".models",
    "albacore_components": ".models",
    "albacore_ranks": ".models",
    "ar": ".models",
    "naive": ".models",
    "hist_mean": ".models",
    "seasonal_naive": ".models",
    "random_walk_drift": ".models",
    "stlf": ".models",
    "arima": ".models",
    "auto_arima": ".models",
    "assemblage_regression": ".models",
    "bayesian_ridge": ".models",
    "bvar_minnesota": ".models",
    "bvar_normal_inverse_wishart": ".models",
    "catboost": ".models",
    "custom_model": ".models",
    "component_aggregation": ".models",
    "dfm_mixed_mariano_murasawa": ".models",
    "dfm_unrestricted_midas": ".models",
    "decision_tree": ".models",
    "describe_model": ".models",
    "density_hnn": ".models",
    "egarch": ".models",
    "gjr_garch": ".models",
    "tgarch": ".models",
    "elastic_net": ".models",
    "ets": ".models",
    "extra_trees": ".models",
    "far": ".models",
    "favar": ".models",
    "fused_difference_ridge": ".models",
    "garch11": ".models",
    "get_model": ".models",
    "glmboost": ".models",
    "gradient_boosting": ".models",
    "group_lasso": ".models",
    "gru": ".models",
    "hemisphere_nn": ".models",
    "huber": ".models",
    "holt_winters": ".models",
    "kernel_ridge": ".models",
    "knn": ".models",
    "lasso": ".models",
    "lgba_plus": ".models",
    "lgb_plus": ".models",
    "lightgbm": ".models",
    "linear_svr": ".models",
    "list_model_specs": ".models",
    "load_fit": ".models",
    "lstm": ".models",
    "macro_random_forest": ".models",
    "mars": ".models",
    "midas_almon": ".models",
    "midas_beta": ".models",
    "midas_step": ".models",
    "restricted_midas": ".models",
    "nn": ".models",
    "model_search_space": ".models",
    "nonneg_ridge": ".models",
    "nu_svr": ".models",
    "ols": ".models",
    "pls": ".models",
    "quantile_regression_forest": ".models",
    "rank_aggregation": ".models",
    "random_walk_ridge": ".models",
    "random_forest": ".models",
    "realized_garch": ".models",
    "ridge": ".models",
    "save_fit": ".models",
    "scaled_pca": ".models",
    "shrink_to_target_ridge": ".models",
    "solve_fused_difference_ridge": ".models",
    "solve_mean_aligned_ridge": ".models",
    "solve_nonnegative_ridge": ".models",
    "solve_simplex_ridge": ".models",
    "solve_target_shrinkage_ridge": ".models",
    "sparse_group_lasso": ".models",
    "supervised_aggregation": ".models",
    "supervised_pca": ".models",
    "supervised_scaled_pca": ".models",
    "svr": ".models",
    "theta_method": ".models",
    "transformer": ".models",
    "tvp_ridge": ".models",
    "unrestricted_midas": ".models",
    "var": ".models",
    "xgboost": ".models",
    "BaggingRegressor": ".model_ensemble",
    "BoogingRegressor": ".model_ensemble",
    "MODEL_ENSEMBLE_BASE_ESTIMATORS": ".model_ensemble",
    "MODEL_ENSEMBLE_SPECS": ".model_ensemble",
    "RandomSubspaceRegressor": ".model_ensemble",
    "StackingRegressor": ".model_ensemble",
    "SuperLearnerRegressor": ".model_ensemble",
    "bagging": ".model_ensemble",
    "booging": ".model_ensemble",
    "custom_model_ensemble": ".model_ensemble",
    "describe_model_ensemble": ".model_ensemble",
    "get_model_ensemble": ".model_ensemble",
    "list_model_ensemble_bases": ".model_ensemble",
    "list_model_ensemble_specs": ".model_ensemble",
    "model_ensemble_search_space": ".model_ensemble",
    "random_subspace": ".model_ensemble",
    "stacking": ".model_ensemble",
    "subagging": ".model_ensemble",
    "super_learner": ".model_ensemble",
    "ParamDistribution": ".model_selection",
    "SearchError": ".model_selection",
    "SearchResult": ".model_selection",
    "SearchSpec": ".model_selection",
    "ValidationSplitterSpec": ".model_selection",
    "bayesian_search": ".model_selection",
    "choice": ".model_selection",
    "custom_search": ".model_selection",
    "cv_path": ".model_selection",
    "explicit_folds": ".model_selection",
    "fixed": ".model_selection",
    "genetic_search": ".model_selection",
    "grid": ".model_selection",
    "log_uniform": ".model_selection",
    "random_search": ".model_selection",
    "randint": ".model_selection",
    "recursive_threefold": ".model_selection",
    "select_params": ".model_selection",
    "search_spec": ".model_selection",
    "uniform": ".model_selection",
    "validation_splitter": ".model_selection",
    "ForecastResult": ".forecasting",
    "CombinationSpec": ".forecasting",
    "combine_best_n": ".forecasting",
    "combine_bates_granger": ".forecasting",
    "combine_granger_ramanathan": ".forecasting",
    "combine_constrained_ls": ".forecasting",
    "combine_eigenvector": ".forecasting",
    "combine_regularized": ".forecasting",
    "combine_linear_pool": ".forecasting",
    "combine_log_pool": ".forecasting",
    "combine_dmspe": ".forecasting",
    "combine_inverse_mspe": ".forecasting",
    "combine_mean": ".forecasting",
    "combine_median": ".forecasting",
    "combine_trimmed_mean": ".forecasting",
    "combine_winsorized_mean": ".forecasting",
    "combination_spec": ".forecasting",
    "custom_combination": ".forecasting",
    "run": ".forecasting",
    "run_forecast": ".forecasting",
    "AlignmentWindow": ".window",
    "EstimationWindow": ".window",
    "Split": ".window",
    "StagePolicy": ".window",
    "TestWindow": ".window",
    "ValWindow": ".window",
    "WindowSpec": ".window",
    "alignment_drop_incomplete": ".window",
    "alignment_keep_missing": ".window",
    "blocked_kfold": ".window",
    "blocked_kfold_split": ".window",
    "custom_stage_policy": ".window",
    "estimation_expanding": ".window",
    "estimation_fixed": ".window",
    "estimation_rolling": ".window",
    "expanding": ".window",
    "expanding_split": ".window",
    "from_cutoffs": ".window",
    "last_block": ".window",
    "last_block_split": ".window",
    "make_splitter": ".window",
    "normalize_window_name": ".window",
    "poos": ".window",
    "poos_split": ".window",
    "random_kfold": ".window",
    "random_kfold_split": ".window",
    "resolve_window": ".window",
    "resolve_stage_policy": ".window",
    "rolling_blocks": ".window",
    "rolling_blocks_split": ".window",
    "split_table": ".window",
    "stage_index": ".window",
    "stage_panel": ".window",
    "stage_policy": ".window",
    "test_origins": ".window",
    "val_blocked_kfold": ".window",
    "val_expanding": ".window",
    "val_last_block": ".window",
    "val_poos": ".window",
    "val_random_kfold": ".window",
    "val_rolling_blocks": ".window",
}

_LAZY_MODULES: tuple[str, ...] = (
    "meta",
    "data",
    "preprocessing",
    "feature_engineering",
    "data_analysis",
    "feature_analysis",
    "feature_diagnostic",
    "analysis",
    "filters",
    "forecast_analysis",
    "forecast_diagnostic",
    "models",
    "model_ensemble",
    "model_selection",
    "forecasting",
    "metrics",
    "tests",
    "evaluation",
    "window",
    "interpretation",
    "output",
    "reporting",
    "pipeline",
)

__all__ = sorted(set(_LAZY_EXPORTS) | set(_LAZY_MODULES))


def __getattr__(name: str) -> Any:
    if name in _LAZY_MODULES:
        module = import_module(f".{name}", __name__)
        globals()[name] = module
        return module
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS) | set(_LAZY_MODULES))
