"""Pandas-first macro forecasting workflow tools."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__version__ = "0.10.0a0"

_LAZY_EXPORTS = {
    "DEFAULT_RANDOM_SEED": ".meta",
    "MetadataLevel": ".meta",
    "StageDefaultScope": ".meta",
    "configure": ".meta",
    "get_config": ".meta",
    "get_option": ".meta",
    "reset_config": ".meta",
    "use_config": ".meta",
    "DataBundle": ".data",
    "DataSpec": ".data",
    "RegimeDirection": ".data",
    "SamePeriodPolicy": ".data",
    "as_panel": ".data",
    "align_frequency": ".data",
    "attach_metadata": ".data",
    "availability_lag": ".data",
    "chow_lin_disaggregate": ".data",
    "custom_dataset": ".data",
    "metadata": ".data",
    "panel_info": ".data",
    "set_frequencies": ".data",
    "spec": ".data",
    "validate_panel": ".data",
    "combine": ".data",
    "define_regime": ".data",
    "frequency_hardening_issues": ".data",
    "infer_frequencies": ".data",
    "list_vintages": ".data",
    "load_custom_csv": ".data",
    "load_custom_parquet": ".data",
    "load_fred_md": ".data",
    "load_fred_qd": ".data",
    "load_fred_sd": ".data",
    "load_fred_md_sd": ".data",
    "load_fred_qd_sd": ".data",
    "same_period_predictors": ".data",
    "PreprocessedData": ".preprocessing",
    "FittedPreprocessor": ".preprocessing",
    "PreprocessSpec": ".preprocessing",
    "preprocess_spec": ".preprocessing",
    "custom_preprocess": ".preprocessing",
    "custom_preprocess_step": ".preprocessing",
    "reprocess": ".preprocessing",
    "standardize_panel": ".preprocessing",
    "FeatureSpec": ".feature_engineering",
    "FeatureSet": ".feature_engineering",
    "FittedFeatureBuilder": ".feature_engineering",
    "adaptive_ma_rf_features": ".feature_engineering",
    "asymmetric_trim_features": ".feature_engineering",
    "average_target": ".feature_engineering",
    "boruta_selection": ".feature_engineering",
    "build_features": ".feature_engineering",
    "compose_features": ".feature_engineering",
    "correlation_selection": ".feature_engineering",
    "cumsum_features": ".feature_engineering",
    "custom_features": ".feature_engineering",
    "custom_step": ".feature_engineering",
    "dfm_features": ".feature_engineering",
    "diff_features": ".feature_engineering",
    "direct_target": ".feature_engineering",
    "feature_matrix": ".feature_engineering",
    "feature_spec": ".feature_engineering",
    "fourier_features": ".feature_engineering",
    "fourier_step": ".feature_engineering",
    "genetic_selection": ".feature_engineering",
    "group_pca": ".feature_engineering",
    "group_pca_step": ".feature_engineering",
    "hamilton_filter_features": ".feature_engineering",
    "hamilton_step": ".feature_engineering",
    "hp_filter_features": ".feature_engineering",
    "interaction_features": ".feature_engineering",
    "interaction_step": ".feature_engineering",
    "lag": ".feature_engineering",
    "lag_step": ".feature_engineering",
    "lags_then_pca": ".feature_engineering",
    "lasso_path_selection": ".feature_engineering",
    "lasso_selection": ".feature_engineering",
    "log_diff_features": ".feature_engineering",
    "log_features": ".feature_engineering",
    "maf_features": ".feature_engineering",
    "maf_step": ".feature_engineering",
    "marx_step": ".feature_engineering",
    "mixed_frequency_lags": ".feature_engineering",
    "moving_average_ladder": ".feature_engineering",
    "moving_average_pca_lags": ".feature_engineering",
    "moving_average_step": ".feature_engineering",
    "nystroem_features": ".feature_engineering",
    "nystroem_step": ".feature_engineering",
    "path_targets": ".feature_engineering",
    "pca_features": ".feature_engineering",
    "pca_step": ".feature_engineering",
    "pca_then_lags": ".feature_engineering",
    "partial_least_squares_features": ".feature_engineering",
    "partial_least_squares_step": ".feature_engineering",
    "pct_change_features": ".feature_engineering",
    "polynomial_features": ".feature_engineering",
    "polynomial_step": ".feature_engineering",
    "random_projection_features": ".feature_engineering",
    "random_projection_step": ".feature_engineering",
    "rfe_selection": ".feature_engineering",
    "rolling_mean": ".feature_engineering",
    "rolling_step": ".feature_engineering",
    "savitzky_golay_features": ".feature_engineering",
    "scale_features": ".feature_engineering",
    "scale_step": ".feature_engineering",
    "season_dummy": ".feature_engineering",
    "season_dummy_step": ".feature_engineering",
    "seasonal_lag": ".feature_engineering",
    "seasonal_lag_step": ".feature_engineering",
    "sliced_inverse_regression_features": ".feature_engineering",
    "sliced_inverse_regression_step": ".feature_engineering",
    "sparse_pca_chen_rohe_features": ".feature_engineering",
    "sparse_pca_chen_rohe_step": ".feature_engineering",
    "stability_selection": ".feature_engineering",
    "time_features": ".feature_engineering",
    "time_step": ".feature_engineering",
    "transform_step": ".feature_engineering",
    "transform_features": ".feature_engineering",
    "varimax_features": ".feature_engineering",
    "varimax_step": ".feature_engineering",
    "variance_selection": ".feature_engineering",
    "wavelet_features": ".feature_engineering",
    "DataSummaryReport": ".data_summary",
    "correlation_matrix": ".data_summary",
    "missing_rates": ".data_summary",
    "missing_summary": ".data_summary",
    "observation_counts": ".data_summary",
    "outlier_summary": ".data_summary",
    "panel_overview": ".data_summary",
    "panel_snapshot": ".data_summary",
    "sample_coverage": ".data_summary",
    "stationarity_tests": ".data_summary",
    "summarize_data": ".data_summary",
    "univariate_summary": ".data_summary",
    "DataAnalysisReport": ".data_analysis",
    "analyze_data": ".data_analysis",
    "changed_cell_count": ".data_analysis",
    "changed_cell_summary": ".data_analysis",
    "changed_cells": ".data_analysis",
    "cleaning_effect_summary": ".data_analysis",
    "compare_panels": ".data_analysis",
    "correlation_shift": ".data_analysis",
    "distribution_shift": ".data_analysis",
    "missing_shift": ".data_analysis",
    "panel_snapshots": ".data_analysis",
    "FeatureDiagnosticReport": ".feature_analysis",
    "compare_feature_stages": ".feature_analysis",
    "custom_feature_diagnostic": ".feature_analysis",
    "diagnose_features": ".feature_analysis",
    "factor_diagnostics": ".feature_analysis",
    "factor_loadings": ".feature_analysis",
    "factor_timeseries": ".feature_analysis",
    "factor_variance": ".feature_analysis",
    "feature_correlation": ".feature_analysis",
    "feature_correlation_matrix": ".feature_analysis",
    "feature_overview": ".feature_analysis",
    "feature_target_correlation": ".feature_analysis",
    "lag_autocorrelation": ".feature_analysis",
    "lag_correlation_decay": ".feature_analysis",
    "lag_diagnostics": ".feature_analysis",
    "marx_diagnostics": ".feature_analysis",
    "marx_weight_decay": ".feature_analysis",
    "selection_similarity": ".feature_analysis",
    "selection_stability": ".feature_analysis",
    "stage_distribution_shift": ".feature_analysis",
    "ForecastDiagnosticReport": ".forecast_analysis",
    "coefficient_trace": ".forecast_analysis",
    "custom_forecast_diagnostic": ".forecast_analysis",
    "dfm_factor_stability": ".forecast_analysis",
    "dfm_idiosyncratic_acf": ".forecast_analysis",
    "diagnose_forecasts": ".forecast_analysis",
    "ensemble_member_contribution": ".forecast_analysis",
    "ensemble_weight_concentration": ".forecast_analysis",
    "ensemble_weights_over_time": ".forecast_analysis",
    "first_vs_last_forecast": ".forecast_analysis",
    "fitted_vs_actual": ".forecast_analysis",
    "forecast_overview": ".forecast_analysis",
    "forecast_scale_view": ".forecast_analysis",
    "hyperparameter_path": ".forecast_analysis",
    "parameter_stability": ".forecast_analysis",
    "residual_autocorrelation": ".forecast_analysis",
    "residual_qq": ".forecast_analysis",
    "residual_report": ".forecast_analysis",
    "rolling_loss": ".forecast_analysis",
    "rolling_training_loss": ".forecast_analysis",
    "select_forecast_origins": ".forecast_analysis",
    "stage_update_trace": ".forecast_analysis",
    "training_loss_trace": ".forecast_analysis",
    "tuning_objective_trace": ".forecast_analysis",
    "tuning_score_distribution": ".forecast_analysis",
    "tuning_trace": ".forecast_analysis",
    "EvaluationReport": ".evaluation",
    "aggregate_scores": ".evaluation",
    "benchmark_comparison": ".evaluation",
    "error_decomposition": ".evaluation",
    "evaluate_report": ".evaluation",
    "filter_oos_period": ".evaluation",
    "regime_scores": ".evaluation",
    "ModelFit": ".models",
    "ModelParameter": ".models",
    "SavedModel": ".models",
    "ModelSpec": ".models",
    "VolatilityFit": ".models",
    "adaptive_elastic_net": ".models",
    "adaptive_lasso": ".models",
    "ar": ".models",
    "bagging": ".models",
    "bayesian_ridge": ".models",
    "booging": ".models",
    "bvar_minnesota": ".models",
    "bvar_normal_inverse_wishart": ".models",
    "catboost": ".models",
    "custom_model": ".models",
    "dfm_mixed_mariano_murasawa": ".models",
    "dfm_unrestricted_midas": ".models",
    "decision_tree": ".models",
    "describe_model": ".models",
    "egarch": ".models",
    "elastic_net": ".models",
    "ets": ".models",
    "extra_trees": ".models",
    "far": ".models",
    "favar": ".models",
    "fused_difference_ridge": ".models",
    "garch11": ".models",
    "get_model": ".models",
    "glmboost": ".models",
    "gradient_boosting": ".models",
    "group_lasso": ".models",
    "gru": ".models",
    "hemisphere_nn": ".models",
    "huber": ".models",
    "holt_winters": ".models",
    "kernel_ridge": ".models",
    "knn": ".models",
    "lasso": ".models",
    "lightgbm": ".models",
    "linear_svr": ".models",
    "list_model_specs": ".models",
    "load_fit": ".models",
    "lstm": ".models",
    "macro_random_forest": ".models",
    "mars": ".models",
    "midas_almon": ".models",
    "midas_beta": ".models",
    "midas_step": ".models",
    "nn": ".models",
    "model_search_space": ".models",
    "nonneg_ridge": ".models",
    "nu_svr": ".models",
    "ols": ".models",
    "pls": ".models",
    "quantile_regression_forest": ".models",
    "random_walk_ridge": ".models",
    "random_forest": ".models",
    "realized_garch": ".models",
    "ridge": ".models",
    "save_fit": ".models",
    "scaled_pca": ".models",
    "shrink_to_target_ridge": ".models",
    "slow_growing_tree": ".models",
    "sparse_group_lasso": ".models",
    "supervised_pca": ".models",
    "supervised_scaled_pca": ".models",
    "svr": ".models",
    "theta_method": ".models",
    "transformer": ".models",
    "unrestricted_midas": ".models",
    "var": ".models",
    "xgboost": ".models",
    "accumulated_local_effect": ".interpretation",
    "attention_weights": ".interpretation",
    "bootstrap_jackknife": ".interpretation",
    "cumulative_r2_contribution": ".interpretation",
    "custom_interpretation": ".interpretation",
    "deep_lift": ".interpretation",
    "dual_decomposition": ".interpretation",
    "fevd": ".interpretation",
    "forecast_decomposition": ".interpretation",
    "friedman_h_interaction": ".interpretation",
    "generalized_irf": ".interpretation",
    "gradient_attribution": ".interpretation",
    "gradient_shap": ".interpretation",
    "group_aggregate": ".interpretation",
    "historical_decomposition": ".interpretation",
    "integrated_gradients": ".interpretation",
    "lasso_inclusion_frequency": ".interpretation",
    "lineage_attribution": ".interpretation",
    "linear_coefficients": ".interpretation",
    "lofo_importance": ".interpretation",
    "lstm_hidden_state": ".interpretation",
    "model_native_linear_coef": ".interpretation",
    "model_native_tree_importance": ".interpretation",
    "mrf_gtvp": ".interpretation",
    "orthogonalised_irf": ".interpretation",
    "partial_dependence": ".interpretation",
    "permutation_importance": ".interpretation",
    "permutation_importance_strobl": ".interpretation",
    "rolling_recompute": ".interpretation",
    "saliency_map": ".interpretation",
    "shap_deep": ".interpretation",
    "shap_importance": ".interpretation",
    "shap_kernel": ".interpretation",
    "shap_linear": ".interpretation",
    "shap_tree": ".interpretation",
    "shap_values": ".interpretation",
    "tree_importance": ".interpretation",
    "transformation_attribution": ".interpretation",
    "ArtifactManifest": ".output",
    "ArtifactRecord": ".output",
    "CompressionFormat": ".output",
    "OutputBundle": ".output",
    "artifact_index": ".output",
    "bundle_outputs": ".output",
    "collect_provenance": ".output",
    "forecast_table": ".output",
    "interpretation_table": ".output",
    "metadata_table": ".output",
    "metric_table": ".output",
    "model_table": ".output",
    "name_outputs": ".output",
    "ranking_table": ".output",
    "run_summary": ".output",
    "selection_table": ".output",
    "select_outputs": ".output",
    "test_table": ".output",
    "write_artifacts": ".output",
    "ReportBundle": ".reporting",
    "ReportTable": ".reporting",
    "figure_data": ".reporting",
    "html_table": ".reporting",
    "latex_table": ".reporting",
    "markdown_table": ".reporting",
    "render_tables": ".reporting",
    "report_bundle": ".reporting",
    "report_table": ".reporting",
    "ParamDistribution": ".selection",
    "SearchError": ".selection",
    "SearchResult": ".selection",
    "SearchSpec": ".selection",
    "bayesian_search": ".selection",
    "choice": ".selection",
    "custom_search": ".selection",
    "cv_path": ".selection",
    "fixed": ".selection",
    "genetic_search": ".selection",
    "grid": ".selection",
    "log_uniform": ".selection",
    "random_search": ".selection",
    "randint": ".selection",
    "select_params": ".selection",
    "search_spec": ".selection",
    "uniform": ".selection",
    "ForecastResult": ".forecasting",
    "CombinationSpec": ".forecasting",
    "combine_best_n": ".forecasting",
    "combine_dmspe": ".forecasting",
    "combine_inverse_mspe": ".forecasting",
    "combine_mean": ".forecasting",
    "combine_median": ".forecasting",
    "combine_trimmed_mean": ".forecasting",
    "combine_winsorized_mean": ".forecasting",
    "combination_spec": ".forecasting",
    "custom_combination": ".forecasting",
    "run": ".forecasting",
    "run_forecast": ".forecasting",
    "AlignmentWindow": ".window",
    "EstimationWindow": ".window",
    "Split": ".window",
    "StagePolicy": ".window",
    "TestWindow": ".window",
    "ValWindow": ".window",
    "WindowSpec": ".window",
    "alignment_drop_incomplete": ".window",
    "alignment_keep_missing": ".window",
    "blocked_kfold": ".window",
    "blocked_kfold_split": ".window",
    "custom_stage_policy": ".window",
    "estimation_expanding": ".window",
    "estimation_fixed": ".window",
    "estimation_rolling": ".window",
    "expanding": ".window",
    "expanding_split": ".window",
    "from_cutoffs": ".window",
    "last_block": ".window",
    "last_block_split": ".window",
    "make_splitter": ".window",
    "normalize_window_name": ".window",
    "poos": ".window",
    "poos_split": ".window",
    "resolve_window": ".window",
    "resolve_stage_policy": ".window",
    "rolling_blocks": ".window",
    "rolling_blocks_split": ".window",
    "split_table": ".window",
    "stage_index": ".window",
    "stage_panel": ".window",
    "stage_policy": ".window",
    "test_origins": ".window",
    "val_blocked_kfold": ".window",
    "val_expanding": ".window",
    "val_last_block": ".window",
    "val_poos": ".window",
    "val_rolling_blocks": ".window",
}

_LAZY_MODULES: tuple[str, ...] = (
    "meta",
    "data",
    "preprocessing",
    "feature_engineering",
    "data_summary",
    "data_analysis",
    "feature_analysis",
    "feature_diagnostic",
    "forecast_analysis",
    "forecast_diagnostic",
    "models",
    "selection",
    "forecasting",
    "metrics",
    "tests",
    "evaluation",
    "window",
    "interpretation",
    "output",
    "reporting",
)

__all__ = sorted(set(_LAZY_EXPORTS) | set(_LAZY_MODULES))


def __getattr__(name: str) -> Any:
    if name in _LAZY_MODULES:
        module = import_module(f".{name}", __name__)
        globals()[name] = module
        return module
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS) | set(_LAZY_MODULES))
