#!/usr/bin/env python3
"""Count standalone callables in macroforecast.functions.

Run after any API change to keep docs/reference/api/standalone_functions/index.md
accurate.

Usage:
    # From repo root:
    python3 tools/count_callables.py
    # Or as a module (works from any directory):
    python3 -m tools.count_callables

Output:
    Prints per-layer callable counts and total.
    Writes docs/_audit/standalone-callable-inventory-<date>.md with the full table.
"""
import inspect
import sys
from datetime import date
from pathlib import Path
from typing import Any

# Ensure repo root is on sys.path so macroforecast is importable when
# running as `python3 tools/count_callables.py` (Python adds the script's
# directory, not the project root, in that case).
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import macroforecast as mf


_LAYER_MODULE_MAP: dict[str, str] = {
    "macroforecast.api.functions.clean": "L2",
    "macroforecast.api.functions.transforms": "L3",
    "macroforecast.api.functions.timeseries": "L4",
    "macroforecast.api.functions.linear": "L4",
    "macroforecast.api.functions.tree": "L4",
    "macroforecast.api.functions.deep": "L4",
    "macroforecast.api.functions.misc": "L4",
    "macroforecast.api.functions.ridge": "L4",
    "macroforecast.api.functions.ridge_variants": "L4",
    "macroforecast.api.functions.midas": "L4",
    "macroforecast.api.functions.metrics": "L5",
    "macroforecast.api.functions.theil_u": "L5",
    "macroforecast.api.functions.tests": "L6",
    "macroforecast.api.functions.importance": "L7",
}

_LAYER_LABELS: dict[str, str] = {
    "L2": "L2 clean",
    "L3": "L3 transforms",
    "L4": "L4 fit",
    "L5": "L5 metrics",
    "L6": "L6 tests",
    "L7": "L7 importance",
}


def collect_callables() -> tuple[list[str], list[str]]:
    """Return (pure_functions, result_classes) from macroforecast.functions."""
    fns = [
        name
        for name in dir(mf.functions)
        if not name.startswith("_")
        and callable(getattr(mf.functions, name))
        and not inspect.isclass(getattr(mf.functions, name))
    ]
    classes = [
        name
        for name in dir(mf.functions)
        if not name.startswith("_") and inspect.isclass(getattr(mf.functions, name))
    ]
    return fns, classes


def group_by_layer(fns: list[str]) -> dict[str, list[str]]:
    """Group function names by layer label using module membership."""
    by_layer: dict[str, list[str]] = {}
    uncategorised: list[str] = []
    for name in fns:
        obj = getattr(mf.functions, name)
        mod = getattr(obj, "__module__", "")
        layer = _LAYER_MODULE_MAP.get(mod)
        if layer is None:
            uncategorised.append(name)
            layer = "other"
        by_layer.setdefault(layer, []).append(name)
    return by_layer


def build_audit_md(
    fns: list[str],
    classes: list[str],
    by_layer: dict[str, list[str]],
    version: str,
    run_date: str,
) -> str:
    """Return markdown text for the audit file."""
    lines = [
        f"# Standalone Callable Inventory — {run_date}",
        "",
        f"Generated by `tools/count_callables.py` on {run_date}.",
        f"macroforecast version: **{version}**",
        "",
        "## Per-layer summary",
        "",
        "| Layer | Count |",
        "|---|---|",
    ]
    for layer_key in ("L2", "L3", "L4", "L5", "L6", "L7"):
        label = _LAYER_LABELS.get(layer_key, layer_key)
        count = len(by_layer.get(layer_key, []))
        lines.append(f"| {label} | {count} |")
    other_count = len(by_layer.get("other", []))
    if other_count:
        lines.append(f"| other (unclassified) | {other_count} |")
    lines += [
        "",
        f"**Total function callables**: {len(fns)}",
        f"**Result dataclasses**: {len(classes)}",
        "",
    ]
    for layer_key in ("L2", "L3", "L4", "L5", "L6", "L7", "other"):
        names = sorted(by_layer.get(layer_key, []))
        if not names:
            continue
        label = _LAYER_LABELS.get(layer_key, layer_key)
        lines += [
            f"## {label} ({len(names)})",
            "",
        ]
        for name in names:
            lines.append(f"- `{name}`")
        lines.append("")
    if classes:
        lines += [
            f"## Result dataclasses ({len(classes)})",
            "",
        ]
        for name in sorted(classes):
            lines.append(f"- `{name}`")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    fns, classes = collect_callables()
    by_layer = group_by_layer(fns)

    version = getattr(mf, "__version__", "unknown")
    run_date = date.today().isoformat()

    # Print to stdout
    print(f"macroforecast.functions callable inventory")
    print(f"Version: {version}")
    print()
    for layer_key in ("L2", "L3", "L4", "L5", "L6", "L7"):
        label = _LAYER_LABELS.get(layer_key, layer_key)
        count = len(by_layer.get(layer_key, []))
        print(f"  {label}: {count} callables")
    other_count = len(by_layer.get("other", []))
    if other_count:
        print(f"  other (unclassified): {other_count} callables")
    print()
    print(f"  Total function callables: {len(fns)}")
    print(f"  Result dataclasses:       {len(classes)}")
    print(f"  Grand total public names: {len(fns) + len(classes)}")

    # Write audit file
    audit_dir = Path(__file__).parent.parent / "docs" / "_audit"
    audit_dir.mkdir(parents=True, exist_ok=True)
    audit_path = audit_dir / f"standalone-callable-inventory-{run_date}.md"
    audit_md = build_audit_md(fns, classes, by_layer, version, run_date)
    audit_path.write_text(audit_md, encoding="utf-8")
    print()
    print(f"  Audit file: {audit_path}")


if __name__ == "__main__":
    main()
