"""macrocast.

Given a standardized macro dataset adapter and a fixed forecasting recipe,
compare forecasting tools under identical information set, sample split,
benchmark, and evaluation protocol.
"""

__version__ = "0.0.0+local"

from .compiler import (
    CompileError,
    CompileResult,
    CompileValidationError,
    CompiledRecipeSpec,
    compile_recipe_dict,
    compile_recipe_yaml,
    SweepPlan,
    SweepPlanError,
    SweepVariant,
    compile_sweep_plan,
    compiled_spec_to_dict,
    load_recipe_yaml,
    run_compiled_recipe,
)
from .execution import (
    ExecutionError,
    ExecutionResult,
    ExecutionSpec,
    SweepResult,
    VariantResult,
    build_execution_spec,
    execute_recipe,
    execute_sweep,
)
from .execution.stat_tests import (
    AXIS_NAMES as STAT_TEST_AXIS_NAMES,
    LEGACY_TO_NEW as STAT_TEST_LEGACY_TO_NEW,
    dispatch_stat_tests,
)
from .compiler.migrations import migrate_legacy_stat_test
from .compiler.override_diff import apply_overrides
from .studies import (
    ABLATION_REPORT_SCHEMA_VERSION,
    AblationSpec,
    REPLICATION_DIFF_SCHEMA_VERSION,
    ReplicationResult,
    STUDY_MANIFEST_SCHEMA_VERSION,
    VariantManifestEntry,
    build_study_manifest,
    execute_ablation,
    execute_replication,
    validate_study_manifest,
)
from .preprocessing import (
    DimensionalityReductionPolicy,
    EvaluationScale,
    FeatureSelectionPolicy,
    InverseTransformPolicy,
    MissingPolicy,
    OutlierPolicy,
    PreprocessContract,
    PreprocessContractError,
    PreprocessFitScope,
    PreprocessOrder,
    PreprocessValidationError,
    ScalingPolicy,
    TargetTransformPolicy,
    TcodePolicy,
    XTransformPolicy,
    build_preprocess_contract,
    check_preprocess_governance,
    is_operational_preprocess_contract,
    preprocess_summary,
    preprocess_to_dict,
)
from .raw import (
    RawArtifactRecord,
    RawDatasetMetadata,
    RawLoadResult,
    RawVersionRequest,
    append_raw_manifest_entry,
    build_raw_artifact_record,
    get_manifest_path,
    get_raw_cache_root,
    get_raw_file_path,
    list_vintages,
    load_fred_md,
    load_fred_qd,
    load_fred_sd,
    normalize_version_request,
    parse_fred_csv,
    read_raw_manifest,
)
from .recipes import (
    RecipeExecutionError,
    RecipeSpec,
    RecipeValidationError,
    RunSpec,
    build_recipe_spec,
    build_run_spec,
    check_recipe_completeness,
    recipe_summary,
)
from .registry import (
    AxisRegistryEntry,
    AxisSelection,
    AxisSelectionMode,
    AxisType,
    SupportStatus,
    axis_governance_table,
    get_axis_registry,
    get_axis_registry_entry,
    get_canonical_layer_order,
)
from .start import macrocast_single_run
from .stage0 import (
    ComparisonContract,
    FixedDesign,
    ReplicationInput,
    Stage0Frame,
    VaryingDesign,
    build_stage0_frame,
    check_stage0_completeness,
    resolve_route_owner,
    stage0_from_dict,
    stage0_summary,
    stage0_to_dict,
)

__all__ = [
    "macrocast_single_run",
    "build_stage0_frame",
    "check_stage0_completeness",
    "resolve_route_owner",
    "stage0_summary",
    "stage0_to_dict",
    "stage0_from_dict",
    "FixedDesign",
    "VaryingDesign",
    "ComparisonContract",
    "ReplicationInput",
    "Stage0Frame",
    "normalize_version_request",
    "list_vintages",
    "get_raw_cache_root",
    "get_manifest_path",
    "get_raw_file_path",
    "build_raw_artifact_record",
    "append_raw_manifest_entry",
    "read_raw_manifest",
    "parse_fred_csv",
    "load_fred_md",
    "load_fred_qd",
    "load_fred_sd",
    "RawVersionRequest",
    "RawDatasetMetadata",
    "RawArtifactRecord",
    "RawLoadResult",
    "build_recipe_spec",
    "build_run_spec",
    "check_recipe_completeness",
    "recipe_summary",
    "RecipeExecutionError",
    "RecipeValidationError",
    "RecipeSpec",
    "RunSpec",
    "build_preprocess_contract",
    "check_preprocess_governance",
    "is_operational_preprocess_contract",
    "preprocess_summary",
    "preprocess_to_dict",
    "PreprocessContractError",
    "PreprocessValidationError",
    "PreprocessContract",
    "TargetTransformPolicy",
    "XTransformPolicy",
    "TcodePolicy",
    "MissingPolicy",
    "OutlierPolicy",
    "ScalingPolicy",
    "DimensionalityReductionPolicy",
    "FeatureSelectionPolicy",
    "PreprocessOrder",
    "PreprocessFitScope",
    "InverseTransformPolicy",
    "EvaluationScale",
    "build_execution_spec",
    "execute_recipe",
    "ExecutionError",
    "ExecutionSpec",
    "ExecutionResult",
    "get_canonical_layer_order",
    "get_axis_registry",
    "get_axis_registry_entry",
    "axis_governance_table",
    "AxisRegistryEntry",
    "AxisSelection",
    "AxisSelectionMode",
    "AxisType",
    "SupportStatus",
    "load_recipe_yaml",
    "compile_recipe_dict",
    "compile_recipe_yaml",
    "compiled_spec_to_dict",
    "run_compiled_recipe",
    "CompileError",
    "CompileValidationError",
    "CompiledRecipeSpec",
    "CompileResult",
    "SweepPlan",
    "SweepVariant",
    "SweepPlanError",
    "SweepResult",
    "VariantResult",
    "VariantManifestEntry",
    "compile_sweep_plan",
    "execute_sweep",
    "build_study_manifest",
    "validate_study_manifest",
    "ABLATION_REPORT_SCHEMA_VERSION",
    "AblationSpec",
    "REPLICATION_DIFF_SCHEMA_VERSION",
    "ReplicationResult",
    "STUDY_MANIFEST_SCHEMA_VERSION",
    "apply_overrides",
    "execute_ablation",
    "execute_replication",
]
