"""macrocast.

Given a standardized macro dataset adapter and a fixed forecasting recipe,
compare forecasting tools under identical information set, sample split,
benchmark, and evaluation protocol.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

__version__ = "0.0.0+local"

_LAZY_EXPORTS = {
    "macrocast_single_run": ".start",
    "NAVIGATOR_SCHEMA_VERSION": ".navigator",
    "REPLICATION_LIBRARY_VERSION": ".navigator",
    "build_navigation_view": ".navigator",
    "canonical_path": ".navigator",
    "compatibility_view": ".navigator",
    "get_replication_entry": ".navigator",
    "list_replication_entries": ".navigator",
    "replication_recipe_yaml": ".navigator",
    "write_replication_recipe": ".navigator",
    "Experiment": ".experiment",
    "forecast": ".experiment",
    "ExperimentRunResult": ".experiment",
    "ExperimentSweepResult": ".experiment",
    "DEFAULT_PROFILE": ".defaults",
    "DEFAULT_PROFILE_NAME": ".defaults",
    "build_default_recipe_dict": ".defaults",
    "custom_feature_block": ".custom",
    "custom_feature_combiner": ".custom",
    "custom_method_extension_contracts": ".custom",
    "custom_model_contract_metadata": ".custom",
    "custom_preprocessor": ".custom",
    "custom_preprocessor_contract_metadata": ".custom",
    "target_transformer": ".custom",
    "target_transformer_contract_metadata": ".custom",
    "CUSTOM_MODEL_CONTRACT_VERSION": ".custom",
    "CUSTOM_PREPROCESSOR_CONTRACT_VERSION": ".custom",
    "TARGET_TRANSFORMER_CONTRACT_VERSION": ".custom",
    "custom_model": ".custom",
    "register_feature_block": ".custom",
    "register_feature_combiner": ".custom",
    "register_preprocessor": ".custom",
    "register_target_transformer": ".custom",
    "register_model": ".custom",
    "get_custom_feature_block": ".custom",
    "get_custom_feature_combiner": ".custom",
    "get_custom_preprocessor": ".custom",
    "get_custom_target_transformer": ".custom",
    "get_custom_model": ".custom",
    "is_custom_feature_block": ".custom",
    "is_custom_feature_combiner": ".custom",
    "is_custom_preprocessor": ".custom",
    "is_custom_target_transformer": ".custom",
    "is_custom_model": ".custom",
    "list_custom_feature_blocks": ".custom",
    "list_custom_feature_combiners": ".custom",
    "list_custom_preprocessors": ".custom",
    "list_custom_target_transformers": ".custom",
    "list_custom_models": ".custom",
    "clear_custom_feature_blocks": ".custom",
    "clear_custom_feature_combiners": ".custom",
    "clear_custom_preprocessors": ".custom",
    "clear_custom_target_transformers": ".custom",
    "clear_custom_models": ".custom",
    "clear_custom_extensions": ".custom",
    "build_design_frame": ".design",
    "check_design_completeness": ".design",
    "resolve_route_owner": ".design",
    "design_summary": ".design",
    "design_to_dict": ".design",
    "design_from_dict": ".design",
    "FixedDesign": ".design",
    "VaryingDesign": ".design",
    "ComparisonContract": ".design",
    "ReplicationInput": ".design",
    "DesignFrame": ".design",
    "normalize_version_request": ".raw",
    "list_vintages": ".raw",
    "get_raw_cache_root": ".raw",
    "get_manifest_path": ".raw",
    "get_raw_file_path": ".raw",
    "build_raw_artifact_record": ".raw",
    "append_raw_manifest_entry": ".raw",
    "read_raw_manifest": ".raw",
    "parse_fred_csv": ".raw",
    "load_custom_csv": ".raw",
    "load_custom_parquet": ".raw",
    "load_fred_md": ".raw",
    "load_fred_qd": ".raw",
    "load_fred_sd": ".raw",
    "RawVersionRequest": ".raw",
    "RawDatasetMetadata": ".raw",
    "RawArtifactRecord": ".raw",
    "RawLoadResult": ".raw",
    "build_recipe_spec": ".recipes",
    "build_run_spec": ".recipes",
    "check_recipe_completeness": ".recipes",
    "recipe_summary": ".recipes",
    "RecipeExecutionError": ".recipes",
    "RecipeValidationError": ".recipes",
    "RecipeSpec": ".recipes",
    "RunSpec": ".recipes",
    "build_preprocess_contract": ".preprocessing",
    "check_preprocess_governance": ".preprocessing",
    "is_operational_preprocess_contract": ".preprocessing",
    "preprocess_summary": ".preprocessing",
    "preprocess_to_dict": ".preprocessing",
    "PreprocessContractError": ".preprocessing",
    "PreprocessValidationError": ".preprocessing",
    "PreprocessContract": ".preprocessing",
    "TargetTransformPolicy": ".preprocessing",
    "XTransformPolicy": ".preprocessing",
    "TcodePolicy": ".preprocessing",
    "MissingPolicy": ".preprocessing",
    "OutlierPolicy": ".preprocessing",
    "ScalingPolicy": ".preprocessing",
    "DimensionalityReductionPolicy": ".preprocessing",
    "FeatureSelectionPolicy": ".preprocessing",
    "PreprocessOrder": ".preprocessing",
    "PreprocessFitScope": ".preprocessing",
    "InverseTransformPolicy": ".preprocessing",
    "EvaluationScale": ".preprocessing",
    "build_execution_spec": ".execution",
    "execute_recipe": ".execution",
    "ExecutionError": ".execution",
    "ExecutionSpec": ".execution",
    "ExecutionResult": ".execution",
    "ForecastPayload": ".execution",
    "DirectionForecastPayload": ".execution",
    "IntervalForecastPayload": ".execution",
    "DensityForecastPayload": ".execution",
    "Layer2Representation": ".execution",
    "LAYER1_OFFICIAL_FRAME_CONTRACT_VERSION": ".execution",
    "LAYER2_REPRESENTATION_CONTRACT_VERSION": ".execution",
    "PREDICTION_ROW_SCHEMA_VERSION": ".execution",
    "SweepResult": ".execution",
    "VariantResult": ".execution",
    "execute_sweep": ".execution",
    "STAT_TEST_AXIS_NAMES": ".execution.stat_tests",
    "STAT_TEST_LEGACY_TO_NEW": ".execution.stat_tests",
    "dispatch_stat_tests": ".execution.stat_tests",
    "get_canonical_layer_order": ".registry",
    "get_axis_registry": ".registry",
    "get_axis_registry_entry": ".registry",
    "axis_governance_table": ".registry",
    "AxisRegistryEntry": ".registry",
    "AxisSelection": ".registry",
    "AxisSelectionMode": ".registry",
    "AxisType": ".registry",
    "SupportStatus": ".registry",
    "load_recipe_yaml": ".compiler",
    "compile_recipe_dict": ".compiler",
    "compile_recipe_yaml": ".compiler",
    "compiled_spec_to_dict": ".compiler",
    "run_compiled_recipe": ".compiler",
    "CompileError": ".compiler",
    "CompileValidationError": ".compiler",
    "CompiledRecipeSpec": ".compiler",
    "CompileResult": ".compiler",
    "SweepPlan": ".compiler",
    "SweepVariant": ".compiler",
    "SweepPlanError": ".compiler",
    "compile_sweep_plan": ".compiler",
    "migrate_legacy_stat_test": ".compiler.migrations",
    "apply_overrides": ".compiler.override_diff",
    "build_study_manifest": ".studies",
    "validate_study_manifest": ".studies",
    "ABLATION_REPORT_SCHEMA_VERSION": ".studies",
    "AblationSpec": ".studies",
    "REPLICATION_DIFF_SCHEMA_VERSION": ".studies",
    "ReplicationResult": ".studies",
    "STUDY_MANIFEST_SCHEMA_VERSION": ".studies",
    "execute_ablation": ".studies",
    "execute_replication": ".studies",
    "execute_separate_runs": ".studies",
    "SeparateRunsResult": ".studies",
    "SEPARATE_RUNS_MANIFEST_SCHEMA_VERSION": ".studies",
    "VariantManifestEntry": ".studies",
    "DECOMPOSITION_RESULT_SCHEMA_VERSION": ".decomposition",
    "DecompositionPlan": ".decomposition",
    "DecompositionResult": ".decomposition",
    "run_decomposition": ".decomposition",
}

__all__ = [
    "macrocast_single_run",
    "NAVIGATOR_SCHEMA_VERSION",
    "REPLICATION_LIBRARY_VERSION",
    "build_navigation_view",
    "canonical_path",
    "compatibility_view",
    "get_replication_entry",
    "list_replication_entries",
    "replication_recipe_yaml",
    "write_replication_recipe",
    "Experiment",
    "forecast",
    "ExperimentRunResult",
    "ExperimentSweepResult",
    "DEFAULT_PROFILE",
    "DEFAULT_PROFILE_NAME",
    "build_default_recipe_dict",
    "custom_feature_block",
    "custom_feature_combiner",
    "custom_method_extension_contracts",
    "custom_model_contract_metadata",
    "custom_preprocessor",
    "custom_preprocessor_contract_metadata",
    "target_transformer",
    "target_transformer_contract_metadata",
    "CUSTOM_MODEL_CONTRACT_VERSION",
    "CUSTOM_PREPROCESSOR_CONTRACT_VERSION",
    "TARGET_TRANSFORMER_CONTRACT_VERSION",
    "custom_model",
    "register_feature_block",
    "register_feature_combiner",
    "register_preprocessor",
    "register_target_transformer",
    "register_model",
    "get_custom_feature_block",
    "get_custom_feature_combiner",
    "get_custom_preprocessor",
    "get_custom_target_transformer",
    "get_custom_model",
    "is_custom_feature_block",
    "is_custom_feature_combiner",
    "is_custom_preprocessor",
    "is_custom_target_transformer",
    "is_custom_model",
    "list_custom_feature_blocks",
    "list_custom_feature_combiners",
    "list_custom_preprocessors",
    "list_custom_target_transformers",
    "list_custom_models",
    "clear_custom_feature_blocks",
    "clear_custom_feature_combiners",
    "clear_custom_preprocessors",
    "clear_custom_target_transformers",
    "clear_custom_models",
    "clear_custom_extensions",
    "build_design_frame",
    "check_design_completeness",
    "resolve_route_owner",
    "design_summary",
    "design_to_dict",
    "design_from_dict",
    "FixedDesign",
    "VaryingDesign",
    "ComparisonContract",
    "ReplicationInput",
    "DesignFrame",
    "normalize_version_request",
    "list_vintages",
    "get_raw_cache_root",
    "get_manifest_path",
    "get_raw_file_path",
    "build_raw_artifact_record",
    "append_raw_manifest_entry",
    "read_raw_manifest",
    "parse_fred_csv",
    "load_custom_csv",
    "load_custom_parquet",
    "load_fred_md",
    "load_fred_qd",
    "load_fred_sd",
    "RawVersionRequest",
    "RawDatasetMetadata",
    "RawArtifactRecord",
    "RawLoadResult",
    "build_recipe_spec",
    "build_run_spec",
    "check_recipe_completeness",
    "recipe_summary",
    "RecipeExecutionError",
    "RecipeValidationError",
    "RecipeSpec",
    "RunSpec",
    "build_preprocess_contract",
    "check_preprocess_governance",
    "is_operational_preprocess_contract",
    "preprocess_summary",
    "preprocess_to_dict",
    "PreprocessContractError",
    "PreprocessValidationError",
    "PreprocessContract",
    "TargetTransformPolicy",
    "XTransformPolicy",
    "TcodePolicy",
    "MissingPolicy",
    "OutlierPolicy",
    "ScalingPolicy",
    "DimensionalityReductionPolicy",
    "FeatureSelectionPolicy",
    "PreprocessOrder",
    "PreprocessFitScope",
    "InverseTransformPolicy",
    "EvaluationScale",
    "build_execution_spec",
    "execute_recipe",
    "ExecutionError",
    "ExecutionSpec",
    "ExecutionResult",
    "ForecastPayload",
    "DirectionForecastPayload",
    "IntervalForecastPayload",
    "DensityForecastPayload",
    "Layer2Representation",
    "LAYER1_OFFICIAL_FRAME_CONTRACT_VERSION",
    "LAYER2_REPRESENTATION_CONTRACT_VERSION",
    "PREDICTION_ROW_SCHEMA_VERSION",
    "get_canonical_layer_order",
    "get_axis_registry",
    "get_axis_registry_entry",
    "axis_governance_table",
    "AxisRegistryEntry",
    "AxisSelection",
    "AxisSelectionMode",
    "AxisType",
    "SupportStatus",
    "load_recipe_yaml",
    "compile_recipe_dict",
    "compile_recipe_yaml",
    "compiled_spec_to_dict",
    "run_compiled_recipe",
    "CompileError",
    "CompileValidationError",
    "CompiledRecipeSpec",
    "CompileResult",
    "SweepPlan",
    "SweepVariant",
    "SweepPlanError",
    "SweepResult",
    "VariantResult",
    "VariantManifestEntry",
    "compile_sweep_plan",
    "execute_sweep",
    "build_study_manifest",
    "validate_study_manifest",
    "ABLATION_REPORT_SCHEMA_VERSION",
    "AblationSpec",
    "REPLICATION_DIFF_SCHEMA_VERSION",
    "ReplicationResult",
    "STUDY_MANIFEST_SCHEMA_VERSION",
    "DECOMPOSITION_RESULT_SCHEMA_VERSION",
    "DecompositionPlan",
    "DecompositionResult",
    "apply_overrides",
    "run_decomposition",
    "execute_ablation",
    "execute_replication",
    "execute_separate_runs",
    "SeparateRunsResult",
    "SEPARATE_RUNS_MANIFEST_SCHEMA_VERSION",
]


def __getattr__(name: str) -> Any:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS))
